### ISSUE TITLE
User can search up a movie

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/ticket-stubs#1]
## 💰 Motivation

Users need to find the movie they watched before recording anything.

## 📐 Plan

Search for a movie and display information about it so the user can make sure it is the movie they watched.

## ✅ Task List

- [x] Create a div with data-view='search-films'
- [x] Create a search form strictly for inputs that are movie titles and the year released
- [x] Create a search form strictly for inputs that are IMDb IDs
- [x] Add a question mark button that opens up a modal that explains to the user what an IMDb ID is and where it can be found should they need it
- [x] Make sure app looks nice on both mobile and desktop
- [x] Create a div with data-view='search-result'
- [x] When the user submits the search form, 
  - [x] Send a request to the OMDB API using the value the user inputted
  - [x] Store the data from the response in an object for the diary entry
  - [x] Use the entry object data to render it in the DOM
  - [x] Add a link to the movie's IMDb page using the IMDb ID property from the response
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
