### ISSUE TITLE
User can create a movie diary entry

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/ticket-stubs#2]
## 💰 Motivation

Users want to record their movie-watching experience.

## 📐 Plan

Create a diary entry form that the user can fill out with the movie info, when they watched the movie, and optional ratings, likes, reviews/notes, and tags.

## ✅ Task List

- [x] Save the data object to the local storage
- [x] Add the search entry object to the last search property of the data object
- [x] Create a div with a modal-view="entry-form"
- [x] Listen for click events on the add entry button on the search result view, which opens up the entry form
- [x] Create a form that creates a diary entry for the movie
  - [x] The movie the user searched for is shown at the top of the form
  - [x] The date can be changed
  - [x] Listen for click events on the stars to rate the movie
  - [x] Listen for click events on the heart to show they liked the movie
  - [x] Add a text input for reviews
  - [x] Listen for click events on the rewatch button to show the user has seen the movie before
  - [x] Add a cancel button that closes the modal
  - [x] Add a save button that adds the form values to an object representing the entry
  - [x] Add the entry to the entries property of the data object
- [x] Add a banner that tells the user that the movie was added to their diary
- [x] Add a navbar that shows the user which view they're on
  - [x] The search button will take them back to the search form
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
