### ISSUE TITLE
User can view entries

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/ticket-stubs#3]
## 💰 Motivation

Users should be able to see past entries.

## 📐 Plan

Render all of the user's entry data.

## ✅ Task List

- [x] Create a div with data-view='diary-view'
- [x] Adjust data.entries.date by separating month, date, and year so the entries are easier to sort and render
- [x] Render the entries with the values from data.entries
- [x] Create a div with data-view='entry-view'
  - [x] Add a 'back' link that will take the user back to the diary view
  - [x] Add an edit button for the next feature
  - [x] Render the entry with the values from data.entries
  - [x] Add a link that shows the user the search result view for the movie
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
