### ISSUE TITLE
User can edit an entry

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/ticket-stubs#4]
## 💰 Motivation

Users should be able to edit their diary entry if they made a mistake or changed their mind about the movie.

## 📐 Plan

Reopen the entry form with the current form values and update the values if the user changes anything.

## ✅ Task List

- [x] Listen for clicks on the edit-delete-entry icon
- [x] Show edit-delete modal
- [x] Close the modal if the done button is clicked
- [x] Show the entry form if an edit button was clicked
- [x] Find the matching entry object in the data model and assign it to the data model's editing property if an edit icon was clicked
- [x] Pre-populate the entry form with the clicked entry's values from the object found in the data model
- [x] Update the entry form's submit handler function to conditionally add a new entry object or update the existing one
- [x] Render the individual entry and diary with the updated values
- [x] Show a banner that tells the user the diary entry was updated
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
