### ISSUE TITLE
User can delete an entry

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/ticket-stubs#5]
## 💰 Motivation

Users might want to delete an entry.

## 📐 Plan

Add a delete button which the user can click to delete the entry data. The entry is removed from the diary view as well.

## ✅ Task List

- [x] Listen for clicks on the delete button on the edit-delete modal
- [x] Create a delete-entry modal
  - [x] If the cancel button is clicked, the delete-entry modal will close and the user will be shown the edit-delete modal again
  - [x] If the delete diary entry button is clicked
    - [x] Remove the entry from the data model
    - [x] Remove the entry from the diary view
     - [x] If the diary entry is the only entry in its month container, remove the month container from the page as well
- [x] Show the diary view
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
