### ISSUE TITLE
User can search for an entry or sort by tags

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/ticket-stubs#6]
## 💰 Motivation

Users might want to look for the entry of a specific movie, or for entries that were tagged with additional info.

## 📐 Plan

Create a search form for the diary entries and only return entries that match the search term/tag.

## ✅ Task List

- [ ] 
- [ ] Ensure that refreshing the pages shows the same view as before refreshing.
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
